services:
  web:
    build: .
    volumes:
      - ./flaskr:/app/flaskr:ro
      - ./tests:/app/tests:ro
      - ./requirements.txt:/app/requirements.txt:ro
      #- ./.env:/app/.env:ro
      - ./start_container.sh:/app/start_container.sh:ro
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql-db
    command: /bin/bash -c "./start_container.sh"
  mysql-db:
    hostname: db
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"